<?php
// Guest pages translation strings (Students hub, UniPD, Erasmus, Corporate Housing)
// Array pattern avoids apostrophe/quote conflicts in Italian strings.
if (!function_exists('th_gt')):
function th_gt($it, $key) {
    $strings = array(

        /* =============== STUDENTS HUB =============== */
        'st_hero_title'  => array('en' => 'Student<br>Housing.', 'it' => 'Alloggi per<br>Studenti.'),
        'st_hero_sub'    => array('en' => 'All-inclusive furnished homes in Padova for UniPD and Erasmus students — one fixed monthly payment, registered contract, zero surprises.', 'it' => 'Case arredate all-inclusive a Padova per studenti UniPD ed Erasmus — un unico canone mensile fisso, contratto registrato, zero sorprese.'),
        'st_intro'       => array('en' => 'Finding student accommodation in Padova usually means juggling deposits, utility bills, unregistered rooms, and paperwork in a language you may not speak. Tailor Homes removes all of that. Our student package is built around <strong>one fixed monthly payment that includes everything</strong> — rent, electricity, water, gas, and Wi-Fi — in a <strong>fully furnished, move-in-ready home</strong>, with a <strong>registered contract</strong> that supports your residency paperwork from day one.', 'it' => "Trovare un alloggio per studenti a Padova di solito significa destreggiarsi tra caparre, bollette, stanze senza contratto e pratiche burocratiche. Tailor Homes elimina tutto questo. Il nostro pacchetto studenti si basa su <strong>un unico canone mensile fisso che include tutto</strong> — affitto, luce, acqua, gas e Wi-Fi — in una <strong>casa completamente arredata e pronta da vivere</strong>, con un <strong>contratto registrato</strong> che supporta le tue pratiche di residenza fin dal primo giorno."),
        'st_pkg_label'   => array('en' => 'The Package', 'it' => 'Il Pacchetto'),
        'st_pkg_title'   => array('en' => 'One payment.<br>Everything included.', 'it' => 'Un solo canone.<br>Tutto incluso.'),
        'st_b1_title'    => array('en' => 'Fixed all-inclusive rent', 'it' => 'Canone fisso all-inclusive'),
        'st_b1_desc'     => array('en' => 'One monthly payment covering rent and utilities — electricity, water, gas, and Wi-Fi. No separate bills, no end-of-stay adjustments to worry about.', 'it' => 'Un unico pagamento mensile che copre affitto e utenze — luce, acqua, gas e Wi-Fi. Nessuna bolletta separata, nessun conguaglio a fine soggiorno di cui preoccuparsi.'),
        'st_b2_title'    => array('en' => 'Registered contract', 'it' => 'Contratto registrato'),
        'st_b2_desc'     => array('en' => 'Every stay comes with a regular, registered rental contract — the document typically required by the Questura for residency procedures and by the university for enrolment paperwork. We provide the documentation you need and guide you through it.', 'it' => "Ogni soggiorno prevede un contratto di locazione regolare e registrato — il documento generalmente richiesto dalla Questura per le pratiche di residenza e dall'università per le pratiche di iscrizione. Ti forniamo la documentazione necessaria e ti accompagniamo passo dopo passo."),
        'st_b3_title'    => array('en' => 'Furnished &amp; move-in ready', 'it' => 'Arredato &amp; pronto da vivere'),
        'st_b3_desc'     => array('en' => 'Bed, desk, equipped kitchen, linen — everything is already there. Arrive with your suitcase and start your semester the same day.', 'it' => 'Letto, scrivania, cucina attrezzata, biancheria — è già tutto pronto. Arriva con la valigia e inizia il semestre lo stesso giorno.'),
        'st_b4_title'    => array('en' => 'Real local support', 'it' => 'Supporto locale reale'),
        'st_b4_desc'     => array('en' => 'A single point of contact in Padova, reachable on WhatsApp, in English and Italian — for check-in, maintenance, and any bureaucratic question during your stay.', 'it' => 'Un unico referente a Padova, raggiungibile su WhatsApp, in italiano e inglese — per check-in, manutenzione e qualsiasi dubbio burocratico durante il soggiorno.'),
        'st_choose_label' => array('en' => 'Choose Your Path', 'it' => 'Scegli il Tuo Percorso'),
        'st_choose_title' => array('en' => 'UniPD or Erasmus?', 'it' => 'UniPD o Erasmus?'),
        'st_choose_desc'  => array('en' => 'The package is the same at heart — but your needs are not. Pick your profile for details tailored to your situation.', 'it' => 'Il cuore del pacchetto è lo stesso — ma le tue esigenze no. Scegli il tuo profilo per i dettagli su misura per la tua situazione.'),
        'st_card_up_title' => array('en' => 'UniPD Students', 'it' => 'Studenti UniPD'),
        'st_card_up_desc'  => array('en' => 'Enrolled at the University of Padova? Medium-term stays built around the academic year, with registered contracts for your residency.', 'it' => "Iscritto all'Università di Padova? Soggiorni a medio termine costruiti attorno all'anno accademico, con contratti registrati per la tua residenza."),
        'st_card_er_title' => array('en' => 'Erasmus Students', 'it' => 'Studenti Erasmus'),
        'st_card_er_desc'  => array('en' => 'Arriving on exchange? Semester-length stays, English-speaking support, and the registered contract you need for your permit paperwork.', 'it' => 'In arrivo per uno scambio? Soggiorni della durata di un semestre, assistenza in inglese e il contratto registrato necessario per le pratiche di soggiorno.'),
        'st_card_btn'    => array('en' => 'Learn more →', 'it' => 'Scopri di più →'),

        /* =============== UNIPD PAGE =============== */
        'up_hero_title'  => array('en' => 'UniPD<br>Students.', 'it' => 'Studenti<br>UniPD.'),
        'up_hero_sub'    => array('en' => 'All-inclusive accommodation in Padova built around the academic year — one fixed monthly payment and a registered contract for your residency.', 'it' => "Alloggi all-inclusive a Padova costruiti attorno all'anno accademico — un unico canone mensile fisso e un contratto registrato per la tua residenza."),
        'up_intro'       => array('en' => 'Studying at the University of Padova means committing to the city for months or years — your home should make that easy, not harder. Tailor Homes offers <strong>medium-term furnished apartments and rooms</strong> designed for UniPD students: <strong>one fixed monthly payment including all utilities</strong>, a <strong>registered rental contract</strong> valid for residency registration, and a local team that answers when you call.', 'it' => "Studiare all'Università di Padova significa vivere la città per mesi o anni — la tua casa dovrebbe semplificarti la vita, non complicarla. Tailor Homes offre <strong>appartamenti e stanze arredati a medio termine</strong> pensati per gli studenti UniPD: <strong>un unico canone mensile fisso con tutte le utenze incluse</strong>, un <strong>contratto di locazione registrato</strong> valido per la registrazione della residenza e un team locale che risponde quando chiami."),
        'up_why_label'   => array('en' => 'Why Tailor Homes', 'it' => 'Perché Tailor Homes'),
        'up_why_title'   => array('en' => 'Made for<br>university life.', 'it' => 'Pensato per<br>la vita universitaria.'),
        'up_b1_title'    => array('en' => 'Academic-year terms', 'it' => "Durate su misura per l'anno accademico"),
        'up_b1_desc'     => array('en' => 'Stays aligned with semesters and the academic calendar — from a few months to the full year, with clear conditions from the start.', 'it' => "Soggiorni allineati ai semestri e al calendario accademico — da pochi mesi all'intero anno, con condizioni chiare fin dall'inizio."),
        'up_b2_title'    => array('en' => 'One fixed payment', 'it' => 'Un unico canone fisso'),
        'up_b2_desc'     => array('en' => 'Rent, electricity, water, gas, and Wi-Fi in a single predictable monthly amount. Budget your student life without surprise bills.', 'it' => 'Affitto, luce, acqua, gas e Wi-Fi in un unico importo mensile prevedibile. Pianifica il tuo budget da studente senza bollette a sorpresa.'),
        'up_b3_title'    => array('en' => 'Registered contract for residency', 'it' => 'Contratto registrato per la residenza'),
        'up_b3_desc'     => array('en' => 'A regular, registered contract is typically required to register your residency in Padova and for many university and municipal procedures. With us, it is part of the package — with support for the paperwork.', 'it' => 'Un contratto regolare e registrato è generalmente necessario per registrare la residenza a Padova e per molte pratiche universitarie e comunali. Con noi fa parte del pacchetto — con supporto per la documentazione.'),
        'up_b4_title'    => array('en' => 'Study-friendly homes', 'it' => 'Case a misura di studio'),
        'up_b4_desc'     => array('en' => 'Furnished apartments with desks, fast Wi-Fi, and equipped kitchens, in well-connected areas of Padova — close to lecture halls, libraries, and daily life.', 'it' => 'Appartamenti arredati con scrivanie, Wi-Fi veloce e cucine attrezzate, in zone ben collegate di Padova — vicino ad aule, biblioteche e alla vita di tutti i giorni.'),
        'up_disc'        => array('en' => 'UniPD students also get <strong>15% off every stay</strong> — for themselves, friends, and family. Verify your student card via WhatsApp to receive your code.', 'it' => 'Gli studenti UniPD hanno inoltre il <strong>15% di sconto su ogni soggiorno</strong> — per sé, amici e famiglia. Verifica la tua tessera universitaria via WhatsApp per ricevere il tuo codice.'),
        'up_cta_heading' => array('en' => 'Ready for<br><em>your year in Padova?</em>', 'it' => 'Pronto per<br><em>il tuo anno a Padova?</em>'),
        'up_cta_text'    => array('en' => 'Tell us your dates and budget — we will propose the right home, all-inclusive, with the contract you need.', 'it' => 'Dicci le tue date e il tuo budget — ti proporremo la casa giusta, all-inclusive, con il contratto di cui hai bisogno.'),

        /* =============== ERASMUS PAGE =============== */
        'er_hero_title'  => array('en' => 'Erasmus<br>Students.', 'it' => 'Studenti<br>Erasmus.'),
        'er_hero_sub'    => array('en' => 'Semester-ready homes in Padova with everything included — and the registered contract you need for your permit and residence paperwork.', 'it' => 'Case pronte per il tuo semestre a Padova con tutto incluso — e il contratto registrato necessario per le pratiche di soggiorno e residenza.'),
        'er_intro'       => array('en' => 'Arriving in a new country for your exchange should be exciting — not a bureaucratic obstacle course. Tailor Homes offers <strong>fully furnished, all-inclusive homes</strong> for Erasmus and exchange students in Padova: <strong>one fixed monthly payment covering rent and all utilities</strong>, flexible semester-length stays, English-speaking support, and a <strong>registered contract</strong> — the document typically requested for Questura appointments, residence registration, and your host-university paperwork.', 'it' => "Arrivare in un nuovo paese per il tuo scambio dovrebbe essere entusiasmante — non un percorso a ostacoli burocratico. Tailor Homes offre <strong>case completamente arredate e all-inclusive</strong> per studenti Erasmus e di scambio a Padova: <strong>un unico canone mensile fisso che copre affitto e tutte le utenze</strong>, soggiorni flessibili della durata di un semestre, assistenza in inglese e un <strong>contratto registrato</strong> — il documento generalmente richiesto per gli appuntamenti in Questura, la registrazione della residenza e le pratiche con l'università ospitante."),
        'er_why_label'   => array('en' => 'Why Tailor Homes', 'it' => 'Perché Tailor Homes'),
        'er_why_title'   => array('en' => 'Land softly.<br>Live fully.', 'it' => 'Atterra sereno.<br>Vivi al massimo.'),
        'er_b1_title'    => array('en' => 'Semester-length flexibility', 'it' => 'Flessibilità a misura di semestre'),
        'er_b1_desc'     => array('en' => 'Stays of five, six, or ten months — matched to your exchange period, not to rigid yearly leases.', 'it' => 'Soggiorni di cinque, sei o dieci mesi — in linea con il tuo periodo di scambio, non con rigidi contratti annuali.'),
        'er_b2_title'    => array('en' => 'Everything in one payment', 'it' => 'Tutto in un unico canone'),
        'er_b2_desc'     => array('en' => 'Rent, electricity, water, gas, and Wi-Fi included in one fixed monthly amount. No Italian utility contracts to open, no bills to decode.', 'it' => 'Affitto, luce, acqua, gas e Wi-Fi inclusi in un unico importo mensile fisso. Nessuna utenza italiana da attivare, nessuna bolletta da decifrare.'),
        'er_b3_title'    => array('en' => 'Paperwork, handled together', 'it' => 'Burocrazia, affrontata insieme'),
        'er_b3_desc'     => array('en' => 'A registered rental contract is typically required for residence registration and, for non-EU students, for permit-of-stay procedures at the Questura. We provide the registered contract and the housing documentation your paperwork calls for — and help you understand each step.', 'it' => 'Un contratto di locazione registrato è generalmente necessario per la registrazione della residenza e, per gli studenti extra-UE, per le pratiche di permesso di soggiorno in Questura. Forniamo il contratto registrato e la documentazione abitativa richiesta dalle tue pratiche — e ti aiutiamo a capire ogni passaggio.'),
        'er_b4_title'    => array('en' => 'English-speaking support', 'it' => 'Assistenza in inglese'),
        'er_b4_desc'     => array('en' => 'From your first message to your last day: check-in in person, WhatsApp support throughout your stay, and honest answers in a language you understand.', 'it' => "Dal primo messaggio all'ultimo giorno: check-in di persona, assistenza su WhatsApp per tutto il soggiorno e risposte chiare in una lingua che capisci."),
        'er_disc'        => array('en' => 'Erasmus students also get <strong>15% off every stay</strong> — for themselves, friends, and family. Verify your Erasmus document via WhatsApp to receive your code.', 'it' => 'Gli studenti Erasmus hanno inoltre il <strong>15% di sconto su ogni soggiorno</strong> — per sé, amici e famiglia. Verifica il tuo documento Erasmus via WhatsApp per ricevere il tuo codice.'),
        'er_cta_heading' => array('en' => 'Ready for<br><em>your semester in Padova?</em>', 'it' => 'Pronto per<br><em>il tuo semestre a Padova?</em>'),
        'er_cta_text'    => array('en' => 'Tell us your exchange dates — we will propose a move-in-ready home with everything included and the documents you need.', 'it' => 'Dicci le date del tuo scambio — ti proporremo una casa pronta da vivere con tutto incluso e i documenti di cui hai bisogno.'),

        /* =============== SHARED (students) =============== */
        'gs_disc_btn'    => array('en' => 'Get Your Discount →', 'it' => 'Richiedi lo Sconto →'),
        'gs_back_students' => array('en' => '← All student housing options', 'it' => '← Tutte le soluzioni per studenti'),
        'gs_cta_btn'     => array('en' => 'Contact Us →', 'it' => 'Contattaci →'),

        /* =============== CORPORATE PAGE =============== */
        'co_hero_title'  => array('en' => 'Corporate<br>Housing.', 'it' => 'Corporate<br>Housing.'),
        'co_hero_sub'    => array('en' => 'Premium short and medium-term accommodation for companies and their people — one point of contact, hotel-grade care, home-like comfort.', 'it' => 'Alloggi premium a breve e medio termine per le aziende e le loro persone — un unico referente, cura di livello alberghiero, comfort di casa.'),
        'co_intro'       => array('en' => 'When your company sends people to Padova — for a project, a trade fair, a relocation, or an extended assignment — a hotel room quickly becomes limiting and a private lease is too rigid. Tailor Homes bridges the gap with <strong>curated, fully serviced apartments</strong> available for <strong>short and medium-term corporate stays</strong>: flexible durations, dedicated corporate rates, unified invoicing, and a single local point of contact from the first booking to the final check-out.', 'it' => "Quando la tua azienda invia persone a Padova — per un progetto, una fiera, una relocation o una trasferta prolungata — una camera di hotel diventa presto limitante e un contratto privato è troppo rigido. Tailor Homes colma questo divario con <strong>appartamenti curati e completamente serviti</strong>, disponibili per <strong>soggiorni aziendali a breve e medio termine</strong>: durate flessibili, tariffe corporate dedicate, fatturazione unificata e un unico referente locale dalla prima prenotazione al check-out finale."),
        'co_why_label'   => array('en' => 'The Corporate Difference', 'it' => 'La Differenza Corporate'),
        'co_why_title'   => array('en' => 'Designed for<br>business. Felt like home.', 'it' => 'Pensato per il business.<br>Vissuto come casa.'),
        'co_b1_title'    => array('en' => 'Short &amp; medium-term flexibility', 'it' => 'Flessibilità a breve &amp; medio termine'),
        'co_b1_desc'     => array('en' => 'From a week at a trade fair to a six-month project assignment — durations shaped around your business calendar, with the option to extend.', 'it' => 'Da una settimana in fiera a una trasferta di progetto di sei mesi — durate modellate sul calendario della tua azienda, con possibilità di estensione.'),
        'co_b2_title'    => array('en' => 'Premium, move-in-ready homes', 'it' => 'Case premium, pronte da vivere'),
        'co_b2_desc'     => array('en' => 'Elegant furnished apartments with fast Wi-Fi, workspaces, equipped kitchens, hotel-grade linen, and professional cleaning — a standard your people will notice.', 'it' => 'Appartamenti arredati con eleganza, Wi-Fi veloce, postazioni di lavoro, cucine attrezzate, biancheria alberghiera e pulizie professionali — uno standard che le tue persone noteranno.'),
        'co_b3_title'    => array('en' => 'One contact, one invoice', 'it' => 'Un referente, una fattura'),
        'co_b3_desc'     => array('en' => 'A dedicated account contact manages every stay, and unified invoicing keeps your administration simple — no matter how many people or properties are involved.', 'it' => 'Un referente dedicato gestisce ogni soggiorno e la fatturazione unificata semplifica la tua amministrazione — indipendentemente dal numero di persone o immobili coinvolti.'),
        'co_b4_title'    => array('en' => 'Dedicated corporate rates', 'it' => 'Tariffe corporate dedicate'),
        'co_b4_desc'     => array('en' => 'Transparent pricing designed for companies, with conditions that improve with recurring stays and longer commitments.', 'it' => 'Prezzi trasparenti pensati per le aziende, con condizioni che migliorano con soggiorni ricorrenti e impegni più lunghi.'),
        'co_use_label'   => array('en' => 'Use Cases', 'it' => 'Casi Tipici'),
        'co_use_title'   => array('en' => 'One solution,<br>many scenarios.', 'it' => 'Una soluzione,<br>molti scenari.'),
        'co_u1'          => array('en' => 'Trade fairs &amp; events', 'it' => 'Fiere &amp; eventi'),
        'co_u2'          => array('en' => 'Project assignments', 'it' => 'Trasferte di progetto'),
        'co_u3'          => array('en' => 'Employee relocation', 'it' => 'Relocation dipendenti'),
        'co_u4'          => array('en' => 'Consultants &amp; contractors', 'it' => 'Consulenti &amp; collaboratori'),
        'co_u5'          => array('en' => 'Medical &amp; academic staff', 'it' => 'Personale medico &amp; accademico'),
        'co_u6'          => array('en' => 'Team accommodation', 'it' => 'Alloggi per team'),
        'co_cta_heading' => array('en' => 'Your team deserves<br><em>better than a hotel.</em>', 'it' => 'Il tuo team merita<br><em>più di un hotel.</em>'),
        'co_cta_text'    => array('en' => 'Tell us who is coming, when, and for how long — we will prepare a tailored corporate proposal within one business day.', 'it' => 'Dicci chi arriva, quando e per quanto tempo — prepareremo una proposta corporate su misura entro un giorno lavorativo.'),
        'co_cta_btn'     => array('en' => 'Request a Proposal →', 'it' => 'Richiedi una Proposta →'),
    );
    $lang = $it ? 'it' : 'en';
    return isset($strings[$key][$lang]) ? $strings[$key][$lang] : $key;
}
endif;
