<?php
// Translation strings - using array to avoid quote conflicts
if (!function_exists('th_t')):
function th_t($it, $key) {
    $strings = array(
        'hero_title'       => array('en' => 'Our<br>Services.',           'it' => 'I Nostri<br>Servizi.'),
        // --- Services hub (Owners vs Guests) ---
        'hub_intro'        => array('en' => 'Tailor Homes works on both sides of every stay. For <strong>property owners</strong>, we provide end-to-end management of short and medium-term rentals. For <strong>guests</strong> — students, professionals, and companies — we offer curated, all-inclusive accommodation in Padova. Choose your path below.', 'it' => "Tailor Homes lavora su entrambi i lati di ogni soggiorno. Per i <strong>proprietari</strong>, offriamo una gestione completa degli affitti brevi e a medio termine. Per gli <strong>ospiti</strong> — studenti, professionisti e aziende — proponiamo alloggi curati e all-inclusive a Padova. Scegli il tuo percorso qui sotto."),
        'hub_owners_label' => array('en' => 'For Property Owners',        'it' => 'Per i Proprietari'),
        'hub_owners_title' => array('en' => 'Your property,<br>fully managed.', 'it' => 'Il tuo immobile,<br>gestito al completo.'),
        'hub_owners_desc'  => array('en' => 'From professional photography and home staging to dynamic pricing, guest care, cleaning, and full legal compliance — we handle everything, and our fee is success-based: we earn only when you earn.', 'it' => "Dalla fotografia professionale e home staging al pricing dinamico, accoglienza ospiti, pulizie e piena conformità legale — ci occupiamo di tutto, con una commissione a successo: guadagniamo solo quando guadagni tu."),
        'hub_owners_p1'    => array('en' => 'Listing, photography &amp; home staging', 'it' => 'Annuncio, fotografia &amp; home staging'),
        'hub_owners_p2'    => array('en' => 'Dynamic pricing &amp; multi-platform visibility', 'it' => 'Pricing dinamico &amp; visibilità multipiattaforma'),
        'hub_owners_p3'    => array('en' => 'Guest welcome, cleaning &amp; property care', 'it' => "Accoglienza, pulizie &amp; cura dell'immobile"),
        'hub_owners_p4'    => array('en' => 'Legal compliance &amp; monthly reporting', 'it' => 'Conformità legale &amp; report mensile'),
        'hub_owners_btn'   => array('en' => 'Explore Owner Services →',   'it' => 'Scopri i Servizi per Proprietari →'),
        'hub_guests_label' => array('en' => 'For Guests',                 'it' => 'Per gli Ospiti'),
        'hub_guests_title' => array('en' => 'A stay tailored<br>to who you are.', 'it' => 'Un soggiorno su misura<br>per chi sei.'),
        'hub_guests_desc'  => array('en' => 'Whether you are studying at the University of Padova, arriving on an Erasmus exchange, or relocating for work — we have an all-inclusive solution designed around your needs.', 'it' => "Che tu stia studiando all'Università di Padova, arrivando con un Erasmus o trasferendoti per lavoro — abbiamo una soluzione all-inclusive pensata per le tue esigenze."),
        'hub_students_title' => array('en' => 'Students — UniPD &amp; Erasmus', 'it' => 'Studenti — UniPD &amp; Erasmus'),
        'hub_students_desc'  => array('en' => 'All-inclusive packages with one fixed monthly payment — utilities included — plus registered contracts that support your residency paperwork.', 'it' => 'Pacchetti all-inclusive con un unico canone mensile fisso — utenze incluse — e contratti registrati che supportano le tue pratiche di residenza.'),
        'hub_corporate_title' => array('en' => 'Corporate Housing',       'it' => 'Corporate Housing'),
        'hub_corporate_desc'  => array('en' => 'Premium short and medium-term accommodation for companies and their teams: business trips, projects, relocations — with a single point of contact.', 'it' => 'Alloggi premium a breve e medio termine per aziende e i loro team: trasferte, progetti, relocation — con un unico referente.'),
        'hub_card_btn'     => array('en' => 'Learn more →',               'it' => 'Scopri di più →'),
        // --- Owners page hero ---
        'own_hero_title'   => array('en' => 'For Property<br>Owners.',    'it' => 'Per i<br>Proprietari.'),
        'own_hero_sub'     => array('en' => 'Full-service management for short and medium-term rentals: one point of contact, tailored care, and a fee we earn only when you do.', 'it' => 'Gestione completa per affitti brevi e a medio termine: un unico interlocutore, cura sartoriale e una commissione che guadagniamo solo quando guadagni tu.'),
        'hero_sub'         => array('en' => 'From full property management to corporate housing for short and medium-term stays: one point of contact, tailored care.', 'it' => 'Dalla gestione completa al corporate housing per soggiorni brevi e a medio termine: un unico interlocutore, una cura sartoriale.'),
        'intro'            => array('en' => 'Tailor Homes provides <strong>end-to-end property management</strong> for short-term and medium-term rentals — covering apartments, <strong>prestige villas</strong>, student stays, and <strong>corporate housing for short and medium-term needs</strong>. Our management fee is <strong>success-based</strong> — when your property earns, we earn. Setup is tailored to each property and discussed transparently from the start.', 'it' => "Tailor Homes offre una <strong>gestione immobiliare completa</strong> per affitti brevi e a medio termine — per appartamenti, <strong>ville di prestigio</strong>, soggiorni studenti e <strong>alloggi aziendali per esigenze brevi e a medio termine</strong>. La nostra commissione di gestione è <strong>basata sul successo</strong> — quando il tuo immobile guadagna, guadagniamo anche noi. Il setup è personalizzato per ogni immobile e discusso in modo trasparente fin dal primo contatto."),
        'what_we_do'       => array('en' => 'What We Do',                 'it' => 'Cosa Facciamo'),
        'complete_mgmt'    => array('en' => 'Complete Property<br>Management.', 'it' => 'Gestione Immobiliare<br>Completa.'),
        'c1_title'         => array('en' => 'Listing &amp; Visibility',   'it' => 'Annuncio &amp; Visibilità'),
        'c1_l1'            => array('en' => 'Professional photography and property styling', 'it' => 'Fotografia professionale e valorizzazione'),
        'c1_l2'            => array('en' => 'Compelling descriptions in multiple languages', 'it' => 'Descrizioni accattivanti in più lingue'),
        'c1_l3'            => array('en' => 'Published on Airbnb, Booking.com, Expedia, and direct channels', 'it' => 'Pubblicato su Airbnb, Booking.com, Expedia e canali diretti'),
        'c1_l4'            => array('en' => 'Dynamic daily pricing to maximise revenue', 'it' => 'Pricing dinamico giornaliero per massimizzare i ricavi'),
        'c2_title'         => array('en' => 'Bookings &amp; Calendar',    'it' => 'Prenotazioni &amp; Calendario'),
        'c2_l1'            => array('en' => 'Real-time calendar sync across all platforms', 'it' => 'Sincronizzazione calendario in tempo reale'),
        'c2_l2'            => array('en' => 'Fast, professional guest communication', 'it' => 'Comunicazione rapida e professionale'),
        'c2_l3'            => array('en' => 'Full payment collected before every check-in', 'it' => 'Pagamento completo prima di ogni check-in'),
        'c2_l4'            => array('en' => 'Zero risk of arrears', 'it' => 'Zero rischio di insoluti'),
        'c3_title'         => array('en' => 'Guest Welcome',              'it' => 'Accoglienza Ospiti'),
        'c3_l1'            => array('en' => 'In-person check-in with full property walkthrough', 'it' => 'Check-in di persona con presentazione completa'),
        'c3_l2'            => array('en' => '24/7 guest assistance during the entire stay', 'it' => 'Assistenza ospiti 24/7 per tutta la durata del soggiorno'),
        'c3_l3'            => array('en' => 'Smooth check-out and post-departure inspection', 'it' => 'Check-out fluido e ispezione post-partenza'),
        'c3_l4'            => array('en' => 'Smart lock and self check-in options available', 'it' => 'Opzioni smart lock e self check-in disponibili'),
        'c4_title'         => array('en' => 'Cleaning &amp; Linen',       'it' => 'Pulizie &amp; Biancheria'),
        'c4_l1'            => array('en' => 'Thorough professional cleaning at every turnover', 'it' => 'Pulizia professionale ad ogni cambio ospite'),
        'c4_l2'            => array('en' => 'Periodic deep-cleaning and maintenance checks', 'it' => 'Pulizie approfondite periodiche e controlli'),
        'c4_l3'            => array('en' => 'Full laundry service with hotel-grade linen', 'it' => 'Servizio lavanderia con biancheria alberghiera'),
        'c4_l4'            => array('en' => 'Welcome kits and premium toiletries', 'it' => 'Kit di benvenuto e articoli da bagno premium'),
        'c5_title'         => array('en' => 'Property Care',              'it' => "Cura dell'Immobile"),
        'c5_l1'            => array('en' => 'Home staging guidance for initial setup', 'it' => 'Consulenza home staging per allestimento'),
        'c5_l2'            => array('en' => 'Continuous monitoring of property condition', 'it' => "Monitoraggio continuo delle condizioni dell'immobile"),
        'c5_l3'            => array('en' => 'Coordination of maintenance and repairs', 'it' => 'Coordinamento manutenzione e riparazioni'),
        'c5_l4'            => array('en' => 'Monthly reporting with full transparency', 'it' => 'Report mensile con piena trasparenza'),
        'c6_title'         => array('en' => 'Legal &amp; Compliance',     'it' => 'Legale &amp; Conformità'),
        'c6_l1'            => array('en' => 'CIN registration and municipal licensing', 'it' => 'Registrazione CIN e licenze comunali'),
        'c6_l2'            => array('en' => 'Guest data reporting to authorities', 'it' => 'Comunicazione dati ospiti alle autorità'),
        'c6_l3'            => array('en' => 'Tourist tax collection and remittance', 'it' => 'Riscossione e versamento tassa di soggiorno'),
        'c6_l4'            => array('en' => 'Dedicated insurance coverage for your property', 'it' => 'Copertura assicurativa dedicata per il tuo immobile'),
        'c7_title'         => array('en' => 'Corporate Housing',          'it' => 'Alloggi Aziendali'),
        'c7_l1'            => array('en' => 'Short and medium-term stays for companies', 'it' => 'Soggiorni brevi e a medio termine per aziende'),
        'c7_l2'            => array('en' => 'Furnished apartments for teams and employees', 'it' => 'Appartamenti arredati per team e dipendenti'),
        'c7_l3'            => array('en' => 'Flexible terms for projects, relocations, and events', 'it' => 'Soluzioni flessibili per progetti, trasferte ed eventi'),
        'c7_l4'            => array('en' => 'Single local contact for booking and support', 'it' => 'Un unico referente locale per prenotazione e assistenza'),
        'beyond'           => array('en' => 'Additional Services',         'it' => 'Servizi Aggiuntivi'),
        'more_ways'        => array('en' => 'We Also Offer.',               'it' => 'Offriamo Anche.'),
        'beyond_intro'     => array('en' => 'Alongside day-to-day management, we support owners with dedicated services to prepare, present, and grow the value of their property: home staging and renovation guidance, professional photography, and investment consulting.', 'it' => "Oltre alla gestione quotidiana, affianchiamo i proprietari con servizi dedicati per preparare, presentare e valorizzare il proprio immobile: home staging e consulenza ristrutturazione, fotografia professionale e consulenza per gli investimenti."),
        'e1_title'         => array('en' => 'Corporate Housing — Short &amp; Medium-Term', 'it' => 'Corporate Housing — Breve &amp; Medio Termine'),
        'e1_desc'          => array('en' => 'Business trips, trade fairs, projects, relocations: accommodation designed for those who travel for work without giving up the feeling of home. Dedicated rates, unified invoicing, and a single point of contact — from day one to the last.', 'it' => "Trasferte, fiere, progetti, relocation: alloggi pensati per chi viaggia per lavoro ma non rinuncia a sentirsi a casa. Tariffe dedicate, fatturazione unificata e un referente unico — dal primo giorno all'ultimo."),
        'e1_t1'            => array('en' => 'Fairs &amp; events',         'it' => 'Fiere &amp; eventi'),
        'e1_t2'            => array('en' => 'Relocations',                'it' => 'Trasferimenti'),
        'e1_t3'            => array('en' => 'Project assignments',        'it' => 'Progetti aziendali'),
        'e1_t4'            => array('en' => 'Student housing',            'it' => 'Alloggi studenti'),
        'e2_title'         => array('en' => 'Home Staging &amp; Renovation', 'it' => 'Home Staging &amp; Ristrutturazione'),
        'e2_desc'          => array('en' => "First impressions define bookings. We guide owners through strategic staging, furniture selection, and targeted renovations — transforming a standard apartment into a property guests want to choose and return to.", 'it' => "Le prime impressioni determinano le prenotazioni. Guidiamo i proprietari nello staging strategico, nella scelta dei mobili e nelle ristrutturazioni mirate — trasformando un appartamento in una proprietà che gli ospiti vogliono scegliere."),
        'e2_t1'            => array('en' => 'Interior styling',           'it' => "Design d'interni"),
        'e2_t2'            => array('en' => 'Furniture curation',         'it' => 'Selezione arredi'),
        'e2_t3'            => array('en' => 'Renovation guidance',        'it' => 'Consulenza ristrutturazione'),
        'e2_t4'            => array('en' => 'Listing-ready prep',         'it' => 'Preparazione annuncio'),
        'e3_title'         => array('en' => 'Professional Photography',   'it' => 'Fotografia Professionale'),
        'e3_desc'          => array('en' => "We offer dedicated photography sessions for your property — capturing every room, every detail, and every quality that makes it worth booking. Beautifully shot images are one of the single most powerful tools for standing out on Airbnb, Booking.com, and your own listings.", 'it' => "Offriamo sessioni fotografiche dedicate al tuo immobile — catturando ogni stanza, ogni dettaglio e ogni qualità che lo rendono degno di essere prenotato. Immagini di qualità sono uno degli strumenti più potenti per distinguersi su Airbnb e Booking.com."),
        'e3_t1'            => array('en' => 'Interior photography',       'it' => 'Fotografia interni'),
        'e3_t2'            => array('en' => 'Ambient &amp; detail shots', 'it' => 'Foto ambientali e dettagli'),
        'e3_t3'            => array('en' => 'Platform-optimised formats', 'it' => 'Formati ottimizzati'),
        'e3_t4'            => array('en' => 'Virtual tour ready',         'it' => 'Tour virtuale'),
        'e4_title'         => array('en' => 'Consulting &amp; Investments', 'it' => 'Consulenza &amp; Investimenti'),
        'e4_desc'          => array('en' => 'We support owners and investors in their most important decisions — from value enhancement to buying and selling. We provide analysis, strategies, and a concrete vision to turn every property into a sustainable investment over time.', 'it' => "Affianchiamo proprietari e investitori nelle decisioni più importanti, dalla valorizzazione alla compravendita. Ti supportiamo con analisi, strategie e visione concreta per trasformare ogni immobile in un investimento sostenibile nel tempo."),
        'e4_t1'            => array('en' => 'Investment analysis',        'it' => 'Analisi investimento'),
        'e4_t2'            => array('en' => 'Buying &amp; selling',       'it' => 'Compravendita'),
        'e4_t3'            => array('en' => 'Strategic advisory',         'it' => 'Consulenza strategica'),
        'e4_t4'            => array('en' => 'Portfolio growth',           'it' => 'Crescita portafoglio'),
        'no_fees'          => array('en' => 'Success-based fee.<br><em>We earn when you earn.</em>', 'it' => 'Commissione a successo.<br><em>Guadagniamo quando guadagni tu.</em>'),
        'no_fees_desc'     => array('en' => "Our management fee is performance-based — a percentage of the rental income you actually generate. This means our interests are perfectly aligned with yours: every decision we make is geared toward maximising your earnings.", 'it' => "La nostra commissione di gestione è basata sulla performance — una percentuale sul reddito che il tuo immobile genera effettivamente. I nostri interessi sono perfettamente allineati ai tuoi: ogni decisione è orientata a massimizzare i tuoi guadagni."),
        'how_it_works'     => array('en' => 'How It Works',               'it' => 'Come Funziona'),
        'four_steps'       => array('en' => 'Four Simple Steps.',         'it' => 'Quattro Semplici Passi.'),
        's1_title'         => array('en' => 'Tell Us About Your Property', 'it' => 'Raccontaci del tuo immobile'),
        's1_desc'          => array('en' => "Share the basics — location, size, condition. We'll assess its short-term rental potential and give you an honest earning estimate.", 'it' => "Condividi le informazioni di base — posizione, dimensioni, condizioni. Valuteremo il potenziale e ti daremo una stima di guadagno realistica."),
        's2_title'         => array('en' => 'We Prepare Everything',      'it' => 'Prepariamo tutto noi'),
        's2_desc'          => array('en' => "Professional photos, listings, pricing strategy, legal compliance — we handle the full setup in the best way, tailored ad-hoc for you.", 'it' => "Foto professionali, annunci, pricing, conformità legale — gestiamo tutto il setup nel modo migliore pensato ad hoc per te."),
        's3_title'         => array('en' => 'Guests Start Booking',       'it' => 'Gli ospiti iniziano a prenotare'),
        's3_desc'          => array('en' => 'Your property goes live across all platforms. We manage every booking, welcome every guest, and keep your property spotless.', 'it' => 'Il tuo immobile va online su tutte le piattaforme. Gestiamo ogni prenotazione e manteniamo la tua proprietà impeccabile.'),
        's4_title'         => array('en' => 'You Earn — Monthly',         'it' => 'Incassi ogni mese'),
        's4_desc'          => array('en' => 'Receive your earnings every month with full reporting. Complete transparency, no guesswork, no stress.', 'it' => 'Ricevi i tuoi guadagni ogni mese con rendiconto completo. Piena trasparenza, nessuna sorpresa.'),
        'faq_label'        => array('en' => 'Common Questions',           'it' => 'Domande Frequenti'),
        'faq_title'        => array('en' => 'Have questions?<br>We have answers.', 'it' => 'Hai domande?<br>Abbiamo le risposte.'),
        'faq1_q'           => array('en' => 'How much can I earn with my property?', 'it' => 'Quanto posso guadagnare con il mio immobile?'),
        'faq1_a'           => array('en' => "We evaluate every aspect — location, condition, seasonality, local demand — and provide a realistic income estimate before you commit. In most cases, professional short-term management outperforms traditional long-term rentals significantly.", 'it' => "Valutiamo ogni aspetto — posizione, condizioni, stagionalità, domanda locale — e forniamo una stima di reddito realistica prima che tu ti impegni. Nella maggior parte dei casi, una gestione professionale supera significativamente gli affitti tradizionali a lungo termine."),
        'faq2_q'           => array('en' => 'Are there any upfront costs or fixed fees?', 'it' => 'Ci sono costi iniziali o commissioni fisse?'),
        'faq2_a'           => array('en' => 'No. Our fee is entirely success-based. We earn a percentage of the rental income only when your property generates bookings. Setup, photos, listing creation, and legal compliance are all included at no extra cost.', 'it' => 'No. La nostra commissione è interamente basata sul successo. Guadagniamo una percentuale sul reddito solo quando il tuo immobile genera prenotazioni. Setup, foto, annunci e conformità legale sono tutti inclusi senza costi aggiuntivi.'),
        'faq3_q'           => array('en' => 'Can I still use my property when I want?', 'it' => 'Posso ancora usare il mio immobile quando voglio?'),
        'faq3_a'           => array('en' => "Absolutely. You retain full ownership and access. Simply block the dates you need, and we'll manage bookings around your schedule.", 'it' => "Assolutamente. Mantieni la piena proprietà e accesso. Blocca semplicemente le date che ti servono e gestiremo le prenotazioni attorno al tuo calendario."),
        'faq4_q'           => array('en' => 'What happens if a guest damages my property?', 'it' => 'Cosa succede se un ospite danneggia il mio immobile?'),
        'faq4_a'           => array('en' => 'We provide dedicated insurance coverage including civil liability protection, property damage protection, and theft protection. Every guest also completes full payment before check-in, and we inspect the property after each stay.', 'it' => "Forniamo una copertura assicurativa dedicata che include responsabilità civile, protezione da danni alla proprietà e furto. Ogni ospite completa il pagamento prima del check-in e ispezioniamo l'immobile dopo ogni soggiorno."),
        'faq5_q'           => array('en' => 'How often will I receive payments?', 'it' => 'Con quale frequenza ricevo i pagamenti?'),
        'faq5_a'           => array('en' => 'Payments are made monthly. You receive a detailed report of all bookings, expenses, and net earnings. Full transparency — no guesswork.', 'it' => 'I pagamenti vengono effettuati mensilmente. Ricevi un rendiconto dettagliato di tutte le prenotazioni, le spese e i guadagni netti. Piena trasparenza.'),
        'faq6_q'           => array('en' => 'Who handles the legal and tax obligations?', 'it' => 'Chi gestisce gli obblighi legali e fiscali?'),
        'faq6_a'           => array('en' => "We take care of everything — CIN registration, municipal licensing, guest reporting to authorities, tourist tax collection, and ongoing regulatory compliance. Your property never goes live without full legal clearance first.", 'it' => "Ci occupiamo di tutto — registrazione CIN, licenze comunali, comunicazione dati ospiti, riscossione tassa di soggiorno e conformità normativa. Il tuo immobile non va mai online senza prima aver ottenuto tutte le autorizzazioni legali."),
        'ask_q_title'      => array('en' => 'Have a question of your own?', 'it' => 'Hai una tua domanda?'),
        'ask_q_text'       => array('en' => 'If your question is not in the list, write to us — we will reply personally.', 'it' => 'Se la tua domanda non è nella lista, scrivici — ti risponderemo personalmente.'),
        'ask_q_btn'        => array('en' => 'Ask Your Question →', 'it' => 'Facci la tua domanda →'),
        'cta_heading'      => array('en' => 'Ready to<br><em>get started?</em>', 'it' => 'Pronto a<br><em>iniziare?</em>'),
        'cta_text'         => array('en' => "Tell us about your property and we'll show you what it could earn. No commitment, no cost — just an honest conversation.", 'it' => "Raccontaci del tuo immobile e ti mostreremo quanto potrebbe guadagnare. Nessun impegno, nessun costo — solo una conversazione onesta."),
        'cta_btn'          => array('en' => 'Contact Us →',               'it' => 'Contattaci →'),
    );
    $lang = $it ? 'it' : 'en';
    return isset($strings[$key][$lang]) ? $strings[$key][$lang] : $key;
}
endif;
