"""Write docs/tailorhomes-students-shotlist.md from timing.json (re-run after analyze_vo.py)."""
import json
from pathlib import Path

C = Path(__file__).resolve().parents[1]
TM = json.loads((C / "timing.json").read_text())
SC, PH, EM = TM["scenes"], TM["phrases"], TM["emphasis"]

ROWS = [
    ("open", [0], "SE1 (S. Eufemia living) in a 900×640 panel under the type",
     "Navy field. Label and salmon rule draw on; italic headline rises word by word from line masks. The panel opens from a line, drifts and lifts, then expands to the photo frame.",
     "Panel → frame expansion (continuous crop, no cut)", "UNIPD · ERASMUS / *Coming to Padova?*", "Whoosh as the panel expands"),
    ("variety1", [1], "SE1 full width above a navy band (photo 0–1235 px)",
     "Slow push-in (1.05 → 1.10) with leftward drift; the headline is set in the band.",
     "—", "YOUR OWN SPACE / *A space that feels like yours.*", "Music groove enters"),
    ("variety2", [1], "VN1 (Via Nullo living, herringbone)",
     "Wall-edge wipe right → left along a thin cream line; Via Nullo enters with parallax; the headline stays.",
     "Wall-edge wipe (match cut S. Eufemia → Via Nullo)", "FURNISHED / headline continues", "Whoosh on the wipe"),
    ("split", [2], "SE4 (S. Eufemia bedroom, beams) top / VN3 (Via Nullo study desk) bottom, navy band between",
     "Halves slide in from opposite sides and drift opposite ways; on exit they part vertically onto cream.",
     "Split screen in; halves part to cream", "A ROOM TO REST · A DESK TO STUDY / *Furnished apartments across Padova.*", "Whoosh"),
    ("benefits", [3], "Cream editorial: VR1 (Vicolo Romano bedroom) large, VN4 (Via Nullo kitchen) + CD1 (Colore & Design reading corner)",
     "Tiles grow and settle in sequence with a slow push; navy tags reveal.",
     "Tiles grow out of the parting split", "FURNISHED · KITCHEN · READING CORNER / *Ready for your stay.*", "Whoosh"),
    ("discount", [4, 5], "Navy, typographic",
     f"Label + rule; italic question; on “fifteen percent” ({EM['fifteen percent']:.2f} s) the question lifts out and the coral −15% pill lands (scale 0.88 → 1, expo out).",
     "Navy cut on the downbeat", "UNIPD & ERASMUS STUDENTS / *UniPD or Erasmus student?* → **−15%** / *15% off your booking.*",
     "Stronger soft impact on the pill"),
    ("claim", [6], "Cream, three glyphs",
     "Student card → chat bubble (check mark draws) → −15% pill, linked by salmon connectors; italic instruction.",
     "Cream slides in from the right", "HOW TO CLAIM · STUDENT CARD · WHATSAPP · DISCOUNT / *Verify your student card via WhatsApp.*",
     "Quiet UI click on the check"),
    ("mosaic", [7], "3×3 mosaic: SE5, VN5, VR2, SE2, CD2, SE3, VN2, VN1 + text cell",
     "Tiles pop in diagonally (fast, no bounce), then collapse to the centre.",
     "Mosaic collapses into the end card", "*Your Padova.* (centre cell)", "Soft tick cluster + whoosh"),
    ("endcard", [8, 9], "Cream end card with the supplied logo",
     "“Your Padova.” → “Your space.” (coral) on the VO; logo fades in on “Tailor Homes”; pill and URL reveal, underline draws. Held 3.2 s after the last word.",
     "—", "*Your Padova. Your space.* / 15% STUDENT DISCOUNT / tailorhomes.it/studenti/", "Final chord, 2.2 s fade"),
]

lines = [f"# Film 02 shotlist — timed to `{TM['source']}`",
         "",
         f"{'**MASTER voice-over**' if TM['is_master'] else '**SCRATCH voice-over** (AI read, timing guide only — replace with the supplied WAV and re-run `scripts/analyze_vo.py`)'}.",
         f"VO duration {TM['vo_duration']:.2f} s, lead-in {TM['lead_in']} s, film {TM['film_duration']:.2f} s at 60 fps.",
         "Generated by `scripts/make_shotlist.py`. Every time below derives from the measured phrase boundaries.",
         "",
         "## Voice phrases (film time)", "", "| # | Start | End | Phrase |", "|---|---|---|---|"]
lines += [f"| {p['i']} | {p['start']:.2f} | {p['end']:.2f} | {p['text']} |" for p in PH]
lines += ["", "Emphasis points: " + ", ".join(f"“{k}” {v:.2f} s" for k, v in EM.items()), "",
          "## Scenes", "",
          "| Scene | Start–end (s) | Voice line | Photos / composition | Animation | Transition | On-screen text | Sound |",
          "|---|---|---|---|---|---|---|---|"]
for key, ph, comp, anim, trans, text, sound in ROWS:
    a, b = SC[key]
    vo = " ".join(f"“{PH[i]['text']}”" for i in ph)
    lines.append(f"| {key} | {a:.2f}–{b:.2f} | {vo} | {comp} | {anim} | {trans} | {text} | {sound} |")
lines += ["", "Safe area for all essential text: x 60–930, y 250–1500 (Instagram Reels UI).", ""]
(C / "docs" / "tailorhomes-students-shotlist.md").write_text("\n".join(lines))
print("shotlist written")
